/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Alert;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author oOo
 */
public class alertMenu extends javax.swing.JFrame {

    /**
     * Creates new form alertMenu
     */
    public alertMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BasicMassage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ErrorMassage = new javax.swing.JButton();
        InformationMassage = new javax.swing.JButton();
        WarningMassage = new javax.swing.JButton();
        QuestionMassage = new javax.swing.JButton();
        PlainMassage = new javax.swing.JButton();
        OptionDialog = new javax.swing.JButton();
        ConfirmDialog = new javax.swing.JButton();
        InputDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        BasicMassage.setBackground(new java.awt.Color(255, 204, 0));
        BasicMassage.setForeground(new java.awt.Color(255, 255, 255));
        BasicMassage.setText("Basic Message");
        BasicMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BasicMassageMouseClicked(evt);
            }
        });
        BasicMassage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicMassageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alert Java");

        ErrorMassage.setBackground(new java.awt.Color(255, 204, 0));
        ErrorMassage.setForeground(new java.awt.Color(255, 255, 255));
        ErrorMassage.setText("Error Message");
        ErrorMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorMassageMouseClicked(evt);
            }
        });
        ErrorMassage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorMassageActionPerformed(evt);
            }
        });

        InformationMassage.setBackground(new java.awt.Color(255, 204, 0));
        InformationMassage.setForeground(new java.awt.Color(255, 255, 255));
        InformationMassage.setText("Information Massage");
        InformationMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformationMassageMouseClicked(evt);
            }
        });
        InformationMassage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationMassageActionPerformed(evt);
            }
        });

        WarningMassage.setBackground(new java.awt.Color(255, 204, 0));
        WarningMassage.setForeground(new java.awt.Color(255, 255, 255));
        WarningMassage.setText("Warning Massage");
        WarningMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WarningMassageMouseClicked(evt);
            }
        });

        QuestionMassage.setBackground(new java.awt.Color(255, 204, 0));
        QuestionMassage.setForeground(new java.awt.Color(255, 255, 255));
        QuestionMassage.setText("Question Massage");
        QuestionMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestionMassageMouseClicked(evt);
            }
        });

        PlainMassage.setBackground(new java.awt.Color(255, 204, 0));
        PlainMassage.setForeground(new java.awt.Color(255, 255, 255));
        PlainMassage.setText("Plain Message");
        PlainMassage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlainMassageMouseClicked(evt);
            }
        });

        OptionDialog.setBackground(new java.awt.Color(255, 204, 0));
        OptionDialog.setForeground(new java.awt.Color(255, 255, 255));
        OptionDialog.setText("Option Dialog");
        OptionDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionDialogMouseClicked(evt);
            }
        });
        OptionDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionDialogActionPerformed(evt);
            }
        });

        ConfirmDialog.setBackground(new java.awt.Color(255, 204, 0));
        ConfirmDialog.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmDialog.setText("Confirm Dialog");
        ConfirmDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmDialogMouseClicked(evt);
            }
        });

        InputDialog.setBackground(new java.awt.Color(255, 204, 0));
        InputDialog.setForeground(new java.awt.Color(255, 255, 255));
        InputDialog.setText("Input Dialog");
        InputDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputDialogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(BasicMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(ErrorMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(InformationMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(WarningMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(QuestionMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(PlainMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(OptionDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(ConfirmDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(InputDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BasicMassage)
                .addGap(18, 18, 18)
                .addComponent(ErrorMassage)
                .addGap(18, 18, 18)
                .addComponent(InformationMassage)
                .addGap(18, 18, 18)
                .addComponent(WarningMassage)
                .addGap(18, 18, 18)
                .addComponent(QuestionMassage)
                .addGap(18, 18, 18)
                .addComponent(PlainMassage)
                .addGap(18, 18, 18)
                .addComponent(OptionDialog)
                .addGap(18, 18, 18)
                .addComponent(ConfirmDialog)
                .addGap(18, 18, 18)
                .addComponent(InputDialog)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BasicMassageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicMassageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BasicMassageActionPerformed

    private void OptionDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionDialogActionPerformed

    private void BasicMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasicMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ini adalah pesan biasa \n @Gagassurya19");
    }//GEN-LAST:event_BasicMassageMouseClicked

    private void ErrorMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contoh : Tidak Dapat Membuka File", "Title : Pesan Error ???", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ErrorMassageMouseClicked

    private void InformationMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformationMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contoh : Data anda berhasil tersimpan !!", "Title : Pesan Informasi ???", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InformationMassageMouseClicked

    private void WarningMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarningMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Contoh : Harap isi data dengan benar", "Title : Pesan Peringatan ???", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_WarningMassageMouseClicked

    private void QuestionMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestionMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Apakah anda ingin keluar?", "Title : Pesan Pertanyaan ???", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_QuestionMassageMouseClicked

    private void PlainMassageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlainMassageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ini cuma pesan pline text", "Title : Pesan Plain ???", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_PlainMassageMouseClicked

    private void OptionDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionDialogMouseClicked
        // TODO add your handling code here:
        Object[] options = {"Yes", "No","Help?"};
        int n = JOptionPane.showOptionDialog(null,
        "Apakah anda sudah mengerti ?",
        "Tanya Jawab",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        options,
        options[2]);
    }//GEN-LAST:event_OptionDialogMouseClicked

    private void ConfirmDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmDialogMouseClicked
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Apakah Mau Keluar","Warning!!", JOptionPane.YES_NO_CANCEL_OPTION);
    }//GEN-LAST:event_ConfirmDialogMouseClicked

    private void InputDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputDialogMouseClicked
        // TODO add your handling code here:
//        String nama = JOptionPane.showInputDialog(null, "Masukan Nama Anda","Informasi Nama", JOptionPane.WARNING_MESSAGE);
//        System.out.println(nama);
        
        //contoh lain
        Component source = (Component) evt.getSource();
        Object response = JOptionPane.showInputDialog(source,
            "Apa yang anda pikirkan saat ini",
            "Select a Destination", JOptionPane.QUESTION_MESSAGE,
            null, new String[] { "A", "B","C", "D", "E" },"A");
        System.out.println("Response: " + response);
    }//GEN-LAST:event_InputDialogMouseClicked

    private void InformationMassageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationMassageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformationMassageActionPerformed

    private void ErrorMassageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorMassageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorMassageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alertMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alertMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alertMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alertMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alertMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasicMassage;
    private javax.swing.JButton ConfirmDialog;
    private javax.swing.JButton ErrorMassage;
    private javax.swing.JButton InformationMassage;
    private javax.swing.JButton InputDialog;
    private javax.swing.JButton OptionDialog;
    private javax.swing.JButton PlainMassage;
    private javax.swing.JButton QuestionMassage;
    private javax.swing.JButton WarningMassage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
