/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Geometri;

/**
 *
 * @author oOo
 */
public class geometri extends javax.swing.JFrame {

    /**
     * Creates new form geometri
     */
    public geometri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jariJari = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        luas = new javax.swing.JLabel();
        inLuas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inKeliling = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Alas = new javax.swing.JLabel();
        inAlasSg = new javax.swing.JTextField();
        HitungSg = new javax.swing.JButton();
        inTinggiSg = new javax.swing.JTextField();
        Tinggi = new javax.swing.JLabel();
        Luas = new javax.swing.JLabel();
        inLuasSg = new javax.swing.JTextField();
        Keliling = new javax.swing.JLabel();
        inKelilingSg = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Sisi = new javax.swing.JLabel();
        inSisiPg = new javax.swing.JTextField();
        Hitung2 = new javax.swing.JButton();
        inLuasPg = new javax.swing.JTextField();
        Luas2 = new javax.swing.JLabel();
        Keliling2 = new javax.swing.JLabel();
        inKelilingPg = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Alas1 = new javax.swing.JLabel();
        inPanjangPp = new javax.swing.JTextField();
        Tinggi1 = new javax.swing.JLabel();
        inLebarPp = new javax.swing.JTextField();
        HitungPp = new javax.swing.JButton();
        inLuasPp = new javax.swing.JTextField();
        Luas1 = new javax.swing.JLabel();
        Keliling1 = new javax.swing.JLabel();
        inKelilingPp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rumus Lingkaran");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jari - Jari :");

        jariJari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jariJariMouseClicked(evt);
            }
        });
        jariJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariJariActionPerformed(evt);
            }
        });

        Hitung.setText("Hitung");
        Hitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungMouseClicked(evt);
            }
        });
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        Hitung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HitungKeyPressed(evt);
            }
        });

        luas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        luas.setForeground(new java.awt.Color(255, 255, 255));
        luas.setText("Luas :");

        inLuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLuasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Keliling :");

        inKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKelilingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jariJari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Hitung, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(luas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jariJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luas)
                    .addComponent(inLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lingkaran", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rumus Segitiga");

        Alas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Alas.setForeground(new java.awt.Color(255, 255, 255));
        Alas.setText("Alas :");

        inAlasSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inAlasSgActionPerformed(evt);
            }
        });

        HitungSg.setText("Hitung");
        HitungSg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungSgMouseClicked(evt);
            }
        });
        HitungSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungSgActionPerformed(evt);
            }
        });
        HitungSg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HitungSgKeyPressed(evt);
            }
        });

        inTinggiSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTinggiSgActionPerformed(evt);
            }
        });

        Tinggi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tinggi.setForeground(new java.awt.Color(255, 255, 255));
        Tinggi.setText("Tinggi :");

        Luas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Luas.setForeground(new java.awt.Color(255, 255, 255));
        Luas.setText("Luas :");

        inLuasSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLuasSgActionPerformed(evt);
            }
        });

        Keliling.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Keliling.setForeground(new java.awt.Color(255, 255, 255));
        Keliling.setText("Keliling :");

        inKelilingSg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKelilingSgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Keliling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inKelilingSg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HitungSg)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Alas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inAlasSg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Tinggi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inTinggiSg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Luas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inLuasSg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alas)
                    .addComponent(inAlasSg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tinggi)
                    .addComponent(inTinggiSg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(HitungSg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Luas)
                    .addComponent(inLuasSg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Keliling)
                    .addComponent(inKelilingSg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Segitiga", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rumus Persegi");

        Sisi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Sisi.setForeground(new java.awt.Color(255, 255, 255));
        Sisi.setText("Sisi :");

        inSisiPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSisiPgActionPerformed(evt);
            }
        });

        Hitung2.setText("Hitung");
        Hitung2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hitung2MouseClicked(evt);
            }
        });
        Hitung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitung2ActionPerformed(evt);
            }
        });
        Hitung2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Hitung2KeyPressed(evt);
            }
        });

        inLuasPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLuasPgActionPerformed(evt);
            }
        });

        Luas2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Luas2.setForeground(new java.awt.Color(255, 255, 255));
        Luas2.setText("Luas :");

        Keliling2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Keliling2.setForeground(new java.awt.Color(255, 255, 255));
        Keliling2.setText("Keliling :");

        inKelilingPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKelilingPgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Keliling2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inKelilingPg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Hitung2)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Sisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inSisiPg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Luas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inLuasPg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sisi)
                    .addComponent(inSisiPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hitung2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Luas2)
                    .addComponent(inLuasPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Keliling2)
                    .addComponent(inKelilingPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persegi", jPanel5);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rumus Persegi Panjang");

        Alas1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Alas1.setForeground(new java.awt.Color(255, 255, 255));
        Alas1.setText("Panjang :");

        inPanjangPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPanjangPpActionPerformed(evt);
            }
        });

        Tinggi1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tinggi1.setForeground(new java.awt.Color(255, 255, 255));
        Tinggi1.setText("Lebar :");

        inLebarPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLebarPpActionPerformed(evt);
            }
        });

        HitungPp.setText("Hitung");
        HitungPp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungPpMouseClicked(evt);
            }
        });
        HitungPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungPpActionPerformed(evt);
            }
        });
        HitungPp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HitungPpKeyPressed(evt);
            }
        });

        inLuasPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLuasPpActionPerformed(evt);
            }
        });

        Luas1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Luas1.setForeground(new java.awt.Color(255, 255, 255));
        Luas1.setText("Luas :");

        Keliling1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Keliling1.setForeground(new java.awt.Color(255, 255, 255));
        Keliling1.setText("Keliling :");

        inKelilingPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKelilingPpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Keliling1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inKelilingPp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HitungPp)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Alas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inPanjangPp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Tinggi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inLebarPp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Luas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inLuasPp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alas1)
                    .addComponent(inPanjangPp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tinggi1)
                    .addComponent(inLebarPp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(HitungPp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Luas1)
                    .addComponent(inLuasPp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Keliling1)
                    .addComponent(inKelilingPp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persegi Panjang", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jariJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariActionPerformed

    private void inLuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLuasActionPerformed

    private void inKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inKelilingActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HitungActionPerformed

    private void HitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungMouseClicked
        // TODO add your handling code here:
        //Mengambil data yang di input
        double r = Double.parseDouble(jariJari.getText());
        //Rumusnya
        double l = Math.PI*r*r;
        double k = Math.PI*r*2;
        //printout hasilnya
        inLuas.setText(String.valueOf(Math.round(l)));
        inKeliling.setText(String.valueOf(k));
    }//GEN-LAST:event_HitungMouseClicked

    private void HitungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HitungKeyPressed
    }//GEN-LAST:event_HitungKeyPressed

    private void inLuasSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLuasSgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLuasSgActionPerformed

    private void inTinggiSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTinggiSgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTinggiSgActionPerformed

    private void HitungSgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HitungSgKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungSgKeyPressed

    private void HitungSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungSgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungSgActionPerformed

    private void HitungSgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungSgMouseClicked
        // TODO add your handling code here:
        double a = Double.parseDouble(inAlasSg.getText());
        double t = Double.parseDouble(inTinggiSg.getText());
        double l = a*t/2;
        double py = Math.pow(a, 2)+Math.pow(t, 2);
        double k = a+t+(Math.sqrt(py));
        inLuasSg.setText(String.valueOf(l));
        inKelilingSg.setText(String.valueOf(k));
    }//GEN-LAST:event_HitungSgMouseClicked

    private void inAlasSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inAlasSgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inAlasSgActionPerformed

    private void inKelilingSgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKelilingSgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inKelilingSgActionPerformed

    private void jariJariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jariJariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariMouseClicked

    private void inPanjangPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPanjangPpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inPanjangPpActionPerformed

    private void inLebarPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLebarPpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLebarPpActionPerformed

    private void HitungPpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungPpMouseClicked
        // TODO add your handling code here:
        double p = Double.parseDouble(inPanjangPp.getText());
        double l = Double.parseDouble(inLebarPp.getText());
        double ls = p*l;
        double k = 2*(p+l);
        inLuasPp.setText(String.valueOf(l));
        inKelilingPp.setText(String.valueOf(k));
    }//GEN-LAST:event_HitungPpMouseClicked

    private void HitungPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungPpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungPpActionPerformed

    private void HitungPpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HitungPpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungPpKeyPressed

    private void inLuasPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLuasPpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLuasPpActionPerformed

    private void inKelilingPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKelilingPpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inKelilingPpActionPerformed

    private void inSisiPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSisiPgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inSisiPgActionPerformed

    private void Hitung2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hitung2MouseClicked
        // TODO add your handling code here:
        double s = Double.parseDouble(inSisiPg.getText());
        double l = s*s;
        double k = 4*s;
        inLuasPg.setText(String.valueOf(l));
        inKelilingPg.setText(String.valueOf(k));
    }//GEN-LAST:event_Hitung2MouseClicked

    private void Hitung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hitung2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hitung2ActionPerformed

    private void Hitung2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hitung2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hitung2KeyPressed

    private void inLuasPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLuasPgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inLuasPgActionPerformed

    private void inKelilingPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKelilingPgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inKelilingPgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(geometri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(geometri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(geometri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(geometri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new geometri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alas;
    private javax.swing.JLabel Alas1;
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Hitung2;
    private javax.swing.JButton HitungPp;
    private javax.swing.JButton HitungSg;
    private javax.swing.JLabel Keliling;
    private javax.swing.JLabel Keliling1;
    private javax.swing.JLabel Keliling2;
    private javax.swing.JLabel Luas;
    private javax.swing.JLabel Luas1;
    private javax.swing.JLabel Luas2;
    private javax.swing.JLabel Sisi;
    private javax.swing.JLabel Tinggi;
    private javax.swing.JLabel Tinggi1;
    private javax.swing.JTextField inAlasSg;
    private javax.swing.JTextField inKeliling;
    private javax.swing.JTextField inKelilingPg;
    private javax.swing.JTextField inKelilingPp;
    private javax.swing.JTextField inKelilingSg;
    private javax.swing.JTextField inLebarPp;
    private javax.swing.JTextField inLuas;
    private javax.swing.JTextField inLuasPg;
    private javax.swing.JTextField inLuasPp;
    private javax.swing.JTextField inLuasSg;
    private javax.swing.JTextField inPanjangPp;
    private javax.swing.JTextField inSisiPg;
    private javax.swing.JTextField inTinggiSg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jariJari;
    private javax.swing.JLabel luas;
    // End of variables declaration//GEN-END:variables
}
